### ISSUE TITLE
無法啟動

### ISSUE THREAD

**Issue by wibe01204** [yeci226/yeci-bot#1]
**資訊如下**
```
C:\Users\bot\Desktop\機器人\yeci-bot>node ./src/Cluster.js
C:\Users\bot\Desktop\機器人\yeci-bot\node_modules\discord-hybrid-sharding\dist\Structures\Data.js:8
        throw new Error('NO CHILD/MASTER EXISTS OR SUPPLIED CLUSTER_MANAGER_MODE IS INCORRECT');
        ^

Error: NO CHILD/MASTER EXISTS OR SUPPLIED CLUSTER_MANAGER_MODE IS INCORRECT
    at getInfo (C:\Users\bot\Desktop\機器人\yeci-bot\node_modules\discord-hybrid-sharding\dist\Structures\Data.js:8:15)
    at Object.<anonymous> (C:\Users\bot\Desktop\機器人\yeci-bot\src\index.js:19:11)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\bot\Desktop\機器人\yeci-bot\src\Cluster.js:1:20)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)

Node.js v20.10.0
```
感謝~

**Comment by yeci226** [comment]
可以提供一下 Cluster.js 嗎

**Comment by wibe01204** [comment]
> 可以提供一下 Cluster.js 嗎

```
const { client } = require("./index.js");
const { ClusterManager, HeartbeatManager } = require("discord-hybrid-sharding");

const manager = new ClusterManager(`${process.cwd()}/src/index.js`, {
  totalShards: "auto",
  totalClusters: "auto",
  shardsPerClusters: 6,
  mode: "worker",
  token: client.config.TOKEN,
});

manager.extend(
  new HeartbeatManager({
    interval: 2000,
    maxMissedHeartbeats: 5,
  })
);

manager.on("clusterCreate", (cluster) =>
  console.log(`Launched Cluster ${cluster.id}`)
);

manager.spawn({ timeout: -1 });

```

**Comment by yeci226** [comment]
https://github.com/yeci226/yeci-bot/commit/c42acfa4878c467e5a5603bc6f98e34551ec2bbb
已修復
